// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instances.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCustomFieldInstanceValue = `-- name: CreateCustomFieldInstanceValue :one
INSERT INTO custom_field_instance_values (id, created_at, updated_at, custom_field_value, instance_id, custom_field_id, username)
VALUES (
    gen_random_uuid()
    ,NOW()
    ,NOW()
    ,$1
    ,$2
    ,$3
    ,$4
)
RETURNING id, created_at, updated_at, custom_field_value, instance_id, custom_field_id, username
`

type CreateCustomFieldInstanceValueParams struct {
	CustomFieldValue string    `json:"custom_field_value"`
	InstanceID       uuid.UUID `json:"instance_id"`
	CustomFieldID    uuid.UUID `json:"custom_field_id"`
	Username         string    `json:"username"`
}

func (q *Queries) CreateCustomFieldInstanceValue(ctx context.Context, arg CreateCustomFieldInstanceValueParams) (CustomFieldInstanceValue, error) {
	row := q.db.QueryRowContext(ctx, createCustomFieldInstanceValue,
		arg.CustomFieldValue,
		arg.InstanceID,
		arg.CustomFieldID,
		arg.Username,
	)
	var i CustomFieldInstanceValue
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomFieldValue,
		&i.InstanceID,
		&i.CustomFieldID,
		&i.Username,
	)
	return i, err
}

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (id, created_at, updated_at, item_id, username)
VALUES (
    gen_random_uuid()
    ,NOW()
    ,NOW()
    ,$1
    ,$2
)
RETURNING id, created_at, updated_at, item_id, username
`

type CreateInstanceParams struct {
	ItemID   uuid.UUID `json:"item_id"`
	Username string    `json:"username"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, createInstance, arg.ItemID, arg.Username)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemID,
		&i.Username,
	)
	return i, err
}
