// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instances.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomFieldInstanceValue = `-- name: CreateCustomFieldInstanceValue :one
INSERT INTO custom_field_instance_values (id, created_at, updated_at, custom_field_value, instance_id, custom_field_id, username)
VALUES (
    gen_random_uuid()
    ,NOW()
    ,NOW()
    ,$1
    ,$2
    ,$3
    ,$4
)
RETURNING id, created_at, updated_at, custom_field_value, instance_id, custom_field_id, username
`

type CreateCustomFieldInstanceValueParams struct {
	CustomFieldValue string    `json:"custom_field_value"`
	InstanceID       uuid.UUID `json:"instance_id"`
	CustomFieldID    uuid.UUID `json:"custom_field_id"`
	Username         string    `json:"username"`
}

func (q *Queries) CreateCustomFieldInstanceValue(ctx context.Context, arg CreateCustomFieldInstanceValueParams) (CustomFieldInstanceValue, error) {
	row := q.db.QueryRowContext(ctx, createCustomFieldInstanceValue,
		arg.CustomFieldValue,
		arg.InstanceID,
		arg.CustomFieldID,
		arg.Username,
	)
	var i CustomFieldInstanceValue
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomFieldValue,
		&i.InstanceID,
		&i.CustomFieldID,
		&i.Username,
	)
	return i, err
}

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (id, created_at, updated_at, item_id, username)
VALUES (
    gen_random_uuid()
    ,NOW()
    ,NOW()
    ,$1
    ,$2
)
RETURNING id, created_at, updated_at, item_id, username
`

type CreateInstanceParams struct {
	ItemID   uuid.UUID `json:"item_id"`
	Username string    `json:"username"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, createInstance, arg.ItemID, arg.Username)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemID,
		&i.Username,
	)
	return i, err
}

const getCustomFieldInstanceValues = `-- name: GetCustomFieldInstanceValues :many
SELECT 
    custom_field_instance_values.custom_field_value
    ,custom_fields.custom_field_name
FROM custom_field_instance_values
JOIN custom_fields ON custom_fields.id = custom_field_instance_values.custom_field_id
WHERE custom_field_instance_values.instance_id = $1
`

type GetCustomFieldInstanceValuesRow struct {
	CustomFieldValue string `json:"custom_field_value"`
	CustomFieldName  string `json:"custom_field_name"`
}

func (q *Queries) GetCustomFieldInstanceValues(ctx context.Context, instanceID uuid.UUID) ([]GetCustomFieldInstanceValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomFieldInstanceValues, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomFieldInstanceValuesRow
	for rows.Next() {
		var i GetCustomFieldInstanceValuesRow
		if err := rows.Scan(&i.CustomFieldValue, &i.CustomFieldName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstances = `-- name: GetInstances :many
SELECT 
    instances.id
    ,instances.created_at
    ,instances.updated_at
    ,items.item_name
    ,items.item_description
    ,items.type_id
    ,instances.username
FROM instances
JOIN items ON items.id = instances.item_id
WHERE instances.username = $1
ORDER BY instances.created_at
`

type GetInstancesRow struct {
	ID              uuid.UUID `json:"id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ItemName        string    `json:"item_name"`
	ItemDescription string    `json:"item_description"`
	TypeID          uuid.UUID `json:"type_id"`
	Username        string    `json:"username"`
}

func (q *Queries) GetInstances(ctx context.Context, username string) ([]GetInstancesRow, error) {
	rows, err := q.db.QueryContext(ctx, getInstances, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstancesRow
	for rows.Next() {
		var i GetInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemName,
			&i.ItemDescription,
			&i.TypeID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
