// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomFieldValue = `-- name: CreateCustomFieldValue :one
INSERT INTO custom_field_values (id, created_at, updated_at, custom_field_value, custom_field_id, item_id, username)
VALUES (
    gen_random_uuid()
    ,NOW()
    ,NOW()
    ,$1
    ,$2
    ,$3
    ,$4
)
RETURNING id, created_at, updated_at, custom_field_value, custom_field_id, item_id, username
`

type CreateCustomFieldValueParams struct {
	CustomFieldValue string    `json:"custom_field_value"`
	CustomFieldID    uuid.UUID `json:"custom_field_id"`
	ItemID           uuid.UUID `json:"item_id"`
	Username         string    `json:"username"`
}

type CreateCustomFieldValueRow struct {
	ID               uuid.UUID `json:"id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	CustomFieldValue string    `json:"custom_field_value"`
	CustomFieldID    uuid.UUID `json:"custom_field_id"`
	ItemID           uuid.UUID `json:"item_id"`
	Username         string    `json:"username"`
}

func (q *Queries) CreateCustomFieldValue(ctx context.Context, arg CreateCustomFieldValueParams) (CreateCustomFieldValueRow, error) {
	row := q.db.QueryRowContext(ctx, createCustomFieldValue,
		arg.CustomFieldValue,
		arg.CustomFieldID,
		arg.ItemID,
		arg.Username,
	)
	var i CreateCustomFieldValueRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomFieldValue,
		&i.CustomFieldID,
		&i.ItemID,
		&i.Username,
	)
	return i, err
}

const createCustomFields = `-- name: CreateCustomFields :one
INSERT INTO custom_fields (id, created_at, updated_at, custom_field_name, custom_field_type, type_id, username)
VALUES (
    gen_random_uuid()
    ,NOW()
    ,NOW()
    ,$1
    ,$2
    ,$3
    ,$4
)
RETURNING id, created_at, updated_at, custom_field_name, custom_field_type, type_id, username
`

type CreateCustomFieldsParams struct {
	CustomFieldName string    `json:"custom_field_name"`
	CustomFieldType string    `json:"custom_field_type"`
	TypeID          uuid.UUID `json:"type_id"`
	Username        string    `json:"username"`
}

func (q *Queries) CreateCustomFields(ctx context.Context, arg CreateCustomFieldsParams) (CustomField, error) {
	row := q.db.QueryRowContext(ctx, createCustomFields,
		arg.CustomFieldName,
		arg.CustomFieldType,
		arg.TypeID,
		arg.Username,
	)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomFieldName,
		&i.CustomFieldType,
		&i.TypeID,
		&i.Username,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, created_at, updated_at, item_name, item_description, type_id, username)
VALUES (
    gen_random_uuid()
    ,NOW()
    ,NOW()
    ,$1
    ,$2
    ,$3
    ,$4
)
RETURNING id, created_at, updated_at, item_name, item_description, type_id, username
`

type CreateItemParams struct {
	ItemName        string    `json:"item_name"`
	ItemDescription string    `json:"item_description"`
	TypeID          uuid.UUID `json:"type_id"`
	Username        string    `json:"username"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ItemName,
		arg.ItemDescription,
		arg.TypeID,
		arg.Username,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemName,
		&i.ItemDescription,
		&i.TypeID,
		&i.Username,
	)
	return i, err
}

const createType = `-- name: CreateType :one
INSERT INTO types (id, created_at, updated_at, type_name, username)
VALUES (
    gen_random_uuid()
    ,NOW()
    ,NOW()
    ,$1
    ,$2
)
RETURNING id, created_at, updated_at, type_name, username
`

type CreateTypeParams struct {
	TypeName string `json:"type_name"`
	Username string `json:"username"`
}

func (q *Queries) CreateType(ctx context.Context, arg CreateTypeParams) (Type, error) {
	row := q.db.QueryRowContext(ctx, createType, arg.TypeName, arg.Username)
	var i Type
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TypeName,
		&i.Username,
	)
	return i, err
}

const getCustomFieldForType = `-- name: GetCustomFieldForType :many
SELECT id, created_at, updated_at, custom_field_name, custom_field_type, type_id, username
FROM custom_fields
WHERE type_id = $1
`

func (q *Queries) GetCustomFieldForType(ctx context.Context, typeID uuid.UUID) ([]CustomField, error) {
	rows, err := q.db.QueryContext(ctx, getCustomFieldForType, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomField
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomFieldName,
			&i.CustomFieldType,
			&i.TypeID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomFieldValues = `-- name: GetCustomFieldValues :many
SELECT 
    custom_fields.custom_field_name
    ,custom_field_values.custom_field_value
FROM custom_field_values
JOIN custom_fields ON custom_fields.id = custom_field_values.custom_field_id
WHERE item_id = $1
ORDER BY custom_fields.created_at
`

type GetCustomFieldValuesRow struct {
	CustomFieldName  string `json:"custom_field_name"`
	CustomFieldValue string `json:"custom_field_value"`
}

func (q *Queries) GetCustomFieldValues(ctx context.Context, itemID uuid.UUID) ([]GetCustomFieldValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomFieldValues, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomFieldValuesRow
	for rows.Next() {
		var i GetCustomFieldValuesRow
		if err := rows.Scan(&i.CustomFieldName, &i.CustomFieldValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomFields = `-- name: GetCustomFields :many
SELECT id, created_at, updated_at, custom_field_name, custom_field_type, type_id, username
FROM custom_fields
ORDER BY created_at
`

func (q *Queries) GetCustomFields(ctx context.Context) ([]CustomField, error) {
	rows, err := q.db.QueryContext(ctx, getCustomFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomField
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomFieldName,
			&i.CustomFieldType,
			&i.TypeID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItems = `-- name: GetItems :many
SELECT id, created_at, updated_at, item_name, item_description, type_id, username
FROM items
ORDER BY created_at
`

func (q *Queries) GetItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemName,
			&i.ItemDescription,
			&i.TypeID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTypeByName = `-- name: GetTypeByName :one
SELECT id, created_at, updated_at, type_name, username
FROM types
WHERE type_name = $1
`

func (q *Queries) GetTypeByName(ctx context.Context, typeName string) (Type, error) {
	row := q.db.QueryRowContext(ctx, getTypeByName, typeName)
	var i Type
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TypeName,
		&i.Username,
	)
	return i, err
}

const getTypes = `-- name: GetTypes :many
SELECT id, created_at, updated_at, type_name, username
FROM types
ORDER BY created_at
`

func (q *Queries) GetTypes(ctx context.Context) ([]Type, error) {
	rows, err := q.db.QueryContext(ctx, getTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Type
	for rows.Next() {
		var i Type
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TypeName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
