// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type AggregateRoll struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	String    string    `json:"string"`
	Result    int32     `json:"result"`
	Username  string    `json:"username"`
}

type Roll struct {
	ID              uuid.UUID `json:"id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	String          string    `json:"string"`
	Result          int32     `json:"result"`
	IndividualRolls string    `json:"individual_rolls"`
	AggregateRollID uuid.UUID `json:"aggregate_roll_id"`
	Username        string    `json:"username"`
}

type User struct {
	Username       string    `json:"username"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	HashedPassword string    `json:"hashed_password"`
}
